Repositories
BohdanRysakov/AjaxOnBoardRysakov pull request #5
Opened 2023-09-08 07:49 UTC by BohdanRysakov

@ajax-shulepa-a 
@ajax-gnatiuk-s

2023-09-08 13:58 UTC, ajax-shulepa-a requested changes

2023-09-08 13:58 UTC, ajax-shulepa-a commented on src/main/kotlin/rys/ajaxpetproject/repository/ChatRepository.kt
> +}
```suggestion
     fun findAllBy() : List<MongoChat>?
}
```

can null list be returned?

2023-09-11 08:10 UTC, BohdanRysakov commented on src/main/kotlin/rys/ajaxpetproject/repository/ChatRepository.kt
> +}
Done

2023-09-11 08:25 UTC, ajax-shulepa-a approved these changes

2023-09-11 08:39 UTC, merged